### ISSUE TITLE
GS.Grooveshark.getStreamingUrl('40425973', function(err, streamUrl) {console.log(err,streamUrl) })

### ISSUE THREAD

**Issue by smolleyes** [xissy/node-grooveshark-streaming#4]
hi

i sometimes have a problem to get streaming url it return 

 GS.Grooveshark.getStreamingUrl('40425973', function(err, streamUrl) {console.log(err,streamUrl) })

-> null 'http://undefined/stream.php?streamKey=undefined'

an idear?

thx !

**Comment by xissy** [comment]
Yes, if a client tries to get streaming urls continually then gooveshark blocks the client based on IP. After a few hours the client can get urls again.
