### ISSUE TITLE
Streaming URL error

### ISSUE THREAD

**Issue by danielfoord** [xissy/node-grooveshark-streaming#6]
Got the songID from the TinySong.getSongInfo, passed the ID along to the GrooveShark.getStreamingUrl and it returns the following streaming url "http://undefined/stream.php?streamKey=undefined"

Any tips ?

**Comment by xissy** [comment]
#4 - Yes, if a client tries to get streaming urls continually then gooveshark blocks the client based on IP. After a few hours the client can get urls again.

**Comment by danielfoord** [comment]
ah that would explain it, thanks :)
