### ISSUE TITLE
Can I implement this legally?

### ISSUE THREAD

**Issue by alexhulbert** [xissy/node-grooveshark-streaming#7]
Hi! I _really_ want to use this library in my project, but I had a question about the legality of the application. The hosting I'm going to be doing is centered in Canada, and I know they have a fancy "Copyright Modernization Act" that _should_ give me the ability to use this. I just figured I'd ask you if you knew anymore about whether I could use this in my program without getting in any trouble.

Thanks!

**Comment by xissy** [comment]
Hello, @Triforce1!
Actually, I couldn't say anything about legal issues, don't know anything about it. This repository is an open sourced project based on my personal interest. I don't want to bother Grooveshark company. :)

Thank you.
